esphome:
    name: hydro-v2-d1mini
    friendly_name: h2-d1
    comment: Hydroponic Manager v2 on d1 Mini
    area: Hydro Greenhouse

esp8266:
    board: d1_mini_lite

# Enable logging
logger:

# Enable Home Assistant API
api:
    encryption:
        key: "84xx8Hu0TjtpfoWOQVPsGMHD9xoifvW8mzeCkCLJ0nw="

ota:
    - platform: esphome
      password: "4c86097e7c772df3a89610d1d68d1e9c"

wifi:
    ssid: !secret wifi_ssid
    password: !secret wifi_password

switch:
    - platform: gpio
      name: "pump1"
      pin:
          number: D1
          inverted: True
    - platform: gpio
      name: "pump2"
      pin:
          number: D2
          inverted: True

binary_sensor:
    - platform: gpio
      name: "overflow"
      filters:
          invert:
      pin:
          number: D3
          mode:
              input: true
              pullup: true
    - platform: gpio
      name: "underflow"
      pin:
          number: D4
          mode:
              input: true
              pullup: true
