esphome:
    name: esp8266-hydro-1
    friendly_name: esp8266 Hydro 1
    comment: Hydroponic Manager
    area: Hydro Greenhouse

esp8266:
    board: d1_mini_lite

logger:

api:
    encryption:
        key: "84xx8Hu0TjtpfoWOQVPsGMHD9xoifvW8mzeCkCLJ0nw="

ota:
    - platform: esphome
      password: "4c86097e7c772df3a89610d1d68d1e9c"

wifi:
    ssid: !secret wifi_ssid
    password: !secret wifi_password

# switch:
#     - platform: gpio
#       name: "solenoid-D3"
#       pin:
#           number: D3
#     - platform: gpio
#       name: "pump-D4"
#       pin:
#           number: D4

binary_sensor:
    - platform: gpio
      name: "water-level-sensor-D1"
      pin:
          number: D1
          mode: INPUT_PULLUP
      filters:
          - delayed_off: 1s
    - platform: gpio
      name: "water-level-sensor-D2"
      pin:
          number: D2
          mode: INPUT_PULLUP
      filters:
          - delayed_off: 1s
