esphome:
    name: esp8266-greenhouse-sensors
    friendly_name: greenhouse-sensors

esp8266:
    board: d1_mini

# Enable logging
logger:

# Enable Home Assistant API
api:
    encryption:
        key: "pfovcbhLjUvbNRAPodnUNjsweQzyScCSm4nL77lopC4="

ota:
    - platform: esphome
      password: "c8525c356c8e7997e4991e90707c3f08"

wifi:
    ssid: !secret wifi_ssid
    password: !secret wifi_password

    # Enable fallback hotspot (captive portal) in case wifi connection fails
    ap:
        ssid: "Greenhouse-Sensors"
        password: "LtAbc22gOJwA"

captive_portal:

i2c:
    sda: d1
    scl: d2
    scan: True
    id: bus_a

sensor:
    - platform: aht10
      variant: AHT20
      i2c_id: bus_a
      update_interval: 5s
      temperature:
          name: "Greenhouse Air Temperature"
          id: aht20_temp
      humidity:
          name: "Greenhouse Air Humidity"
          id: aht20_humidity
