esphome:
    name: esp8266-greenhouse
    friendly_name: greenhouse

esp8266:
    board: d1_mini

# Enable logging
logger:

# Enable Home Assistant API
api:
    encryption:
        key: "pfovcbhLjUvbNRAPodnUNjsweQzyScCSm4nL77lopC4="

ota:
    - platform: esphome
      password: "c8525c356c8e7997e4991e90707c3f08"

wifi:
    ssid: !secret wifi_ssid
    password: !secret wifi_password

    # Enable fallback hotspot (captive portal) in case wifi connection fails
    ap:
        ssid: "greenhouse"
        password: "LtAbc22gOJwA"

captive_portal:

one_wire:
    - platform: gpio
      pin: D5
      id: bus1

# i2c:
#     sda: GPIO4
#     scl: GPIO5
#     scan: True
#     id: bus_a
#     frequency: 100kHz

sensor:
    - name: thermometer-water
      platform: dallas_temp
      unit_of_measurement: "°C"
      one_wire_id: bus1

    - name: soil-moisture
      platform: adc
      pin: A0
      id: soil_moisture
      unit_of_measurement: "%"
      filters:
          - lambda: |-
                // if over 0.740 volts, we are dry
                if (x > 0.740) { return 0; }
                // if under 0.310 volts, we are fully saturated
                else if (x < 0.310) { return 100; }
                // use a linear fit for any values in between
                else {
                    return (((x-0.310)/(0.740-0.310))-1)*100;
                }

    # - platform: aht10
    #   i2c_id: bus_a
    #   update_interval: 5s
    #   temperature:
    #       name: "Greenhouse Air Temperature"
    #       id: aht20_temp
    #   humidity:
    #       name: "Greenhouse Air Humidity"
    #       id: aht20_humidity
