esphome:
    name: esp8266-freezer-temperature-1
    friendly_name: ft1

esp8266:
    board: d1_mini_lite

# Enable logging
logger:

# Enable Home Assistant API
api:
    encryption:
        key: "J72CxGs5sFG78+C0ArX5l8A9mh6n7+ZYCQXC9qAR22Q="

ota:
    - platform: esphome
      password: "b9e8826699336368d5114e46d68aa8ed"

wifi:
    ssid: !secret wifi_ssid
    password: !secret wifi_password

    # Enable fallback hotspot (captive portal) in case wifi connection fails
    ap:
        ssid: "Freezer-Temperature-1"
        password: "HSozygruqANq"

captive_portal:

# Example configuration entry
sensor:
    - platform: ntc
      sensor: resistance_sensor
      unit_of_measurement: "°F"
      icon: "mdi:water-percent"
      device_class: "temperature"
      state_class: "measurement"
      calibration:
          b_constant: 3950
          reference_temperature: 25°C
          reference_resistance: 10kOhm
      name: NTC Temperature

    # Example source sensors:
    - platform: resistance
      id: resistance_sensor
      sensor: source_sensor
      configuration: DOWNSTREAM
      resistor: 10kOhm
      name: Resistance Sensor

    - platform: adc
      id: source_sensor
      pin: A0
      update_interval: never

switch:
    - platform: gpio
      pin: D0
      id: ntc_vcc

interval:
    - interval: 60s
      then:
          - switch.turn_on: ntc_vcc
          - component.update: source_sensor
          - switch.turn_off: ntc_vcc
