esphome:
    name: sensors-4
    friendly_name: sensors-4

esp8266:
    board: d1_mini

# Enable logging
logger:

# Enable Home Assistant API
api:
    encryption:
        key: "HABvio0LnWv725y3s/eAK99/n3oH8U2tx9EzGStACLY="

ota:
    - platform: esphome
      password: "c2698eb5c7e7b00c3212c11929e92880"

wifi:
    ssid: !secret wifi_ssid
    password: !secret wifi_password

    # Enable fallback hotspot (captive portal) in case wifi connection fails
    ap:
        ssid: "Sensors-4 Fallback Hotspot"
        password: "aUMK16eK4lB1"

captive_portal:

one_wire:
    - platform: gpio
      pin: D1
      id: bus1

sensor:
    - platform: dallas_temp
      name: temperature
      id: temperature
      one_wire_id: bus1
      unit_of_measurement: "°C"

    - platform: adc
      name: tds
      pin: A0
      unit_of_measurement: ppm
      filters:
          - multiply: 3.3 # 3.3v from 0-1
          - lambda: return x/(1.0+(0.02 * (id(temperature).state-25.0))); # temp adjustment
          - lambda: return ((133.42 * x * x * x) - (255.86 * x * x) + (857.39 * x)) * 0.5; # v to tds conversion
          - multiply: 0.85 # k value calibration
          #   - multiply: 0.002 # conversion to ec (ec * 500 = tds)
          - sliding_window_moving_average:
                window_size: 20
                send_every: 20
