esphome:
    name: esp8266-freezer-temperature-1
    friendly_name: ft1
esp8266:
    board: d1_mini
logger:
api:
    encryption:
        key: "J72CxGs5sFG78+C0ArX5l8A9mh6n7+ZYCQXC9qAR22Q="
ota:
    - platform: esphome
      password: "b9e8826699336368d5114e46d68aa8ed"
wifi:
    ssid: !secret wifi_ssid
    password: !secret wifi_password
    # Enable fallback hotspot (captive portal) in case wifi connection fails
    ap:
        ssid: "Freezer-Temperature-1"
        password: "HSozygruqANq"
captive_portal:
sensor:
    # Thermocoupler
    - platform: dallas_temp
      name: Dallas Temperature
      icon: "mdi:snowflake-thermometer"
      one_wire_id: bus1
      filters:
          - lambda: return x * (9.0/5.0) + 32.0;
      unit_of_measurement: "°F"
one_wire:
    - platform: gpio
      pin: D5
      id: bus1
