esphome:
    name: thermometer-2
    friendly_name: Thermometer 2

esp8266:
    board: d1_mini

# Enable logging
logger:

# Enable Home Assistant API
api:
    encryption:
        key: "ozXXG4s2a2MLSoHBsMn/6E3EWInBvMdCv4P0CABbwdY="

ota:
    - platform: esphome
      password: "7cc29b1e30d7a89d95101b0e1c49435a"

wifi:
    ssid: !secret wifi_ssid
    password: !secret wifi_password

    # Enable fallback hotspot (captive portal) in case wifi connection fails
    ap:
        ssid: "Thermometer-2 Fallback Hotspot"
        password: "RdnBtBW7kH0R"

captive_portal:

sensor:
    # Thermocoupler
    - platform: dallas_temp
      name: Thermometer
      icon: "mdi:thermometer"
      one_wire_id: bus1
      filters:
          - lambda: return x * (9.0/5.0) + 32.0;
      unit_of_measurement: "°F"
      update_interval: 15s

one_wire:
    - platform: gpio
      pin: D0
      id: bus1
